### ISSUE TITLE
Invalid address; only deSEC <skript@sub.domain.de> could be parsed from "deSEC <skript@sub.domain.de>

### ISSUE THREAD

**Issue by dwydler** [desec-io/desec-stack#863]
Hello desec Team,
i try to setup the desec-stack in my test enviroment to test some css changes.

Basiclly the containers are running. But if i setup an account over the UI i get follow error message in the log of "desec-stack-celery-email-1".
```
desec-stack-celery-email-1            | [2023-12-31 11:54:43,694: ERROR/ForkPoolWorker-8] Celery ValueError in email_slow_lane
desec-stack-celery-email-1            | Traceback (most recent call last):
desec-stack-celery-email-1            |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
desec-stack-celery-email-1            |     R = retval = fun(*args, **kwargs)
desec-stack-celery-email-1            |                  ^^^^^^^^^^^^^^^^^^^^
desec-stack-celery-email-1            |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
desec-stack-celery-email-1            |     return self.run(*args, **kwargs)
desec-stack-celery-email-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^
desec-stack-celery-email-1            |   File "/usr/src/app/desecapi/mail_backends.py", line 41, in _run_task
desec-stack-celery-email-1            |     return connection.send_messages(
desec-stack-celery-email-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^
desec-stack-celery-email-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 135, in send_messages
desec-stack-celery-email-1            |     sent = self._send(message)
desec-stack-celery-email-1            |            ^^^^^^^^^^^^^^^^^^^
desec-stack-celery-email-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 148, in _send
desec-stack-celery-email-1            |     from_email = sanitize_address(email_message.from_email, encoding)
desec-stack-celery-email-1            |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
desec-stack-celery-email-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/message.py", line 92, in sanitize_address
desec-stack-celery-email-1            |     raise ValueError(
desec-stack-celery-email-1            | ValueError: Invalid address; only deSEC <skript@sub.domain.de> could be parsed from "deSEC <skript@sub.domain.de>
desec-stack-celery-email-1            | "
desec-stack-celery-email-1            | [2023-12-31 11:54:43,729: INFO/MainProcess] Task email_slow_lane[ebe99837-7cd7-4adb-9ac1-30a98169afbd] received
desec-stack-celery-email-1            | [2023-12-31 11:54:43,729: ERROR/ForkPoolWorker-8] Task email_slow_lane[cab25782-388f-4ec8-a443-e000854e823f] raised unexpected: ValueError('Invalid address; only deSEC <skript@sub.domain.de> could be parsed from "deSEC <skript@sub.domain.de>\n"')
desec-stack-celery-email-1            | Traceback (most recent call last):
desec-stack-celery-email-1            |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
desec-stack-celery-email-1            |     R = retval = fun(*args, **kwargs)
desec-stack-celery-email-1            |                  ^^^^^^^^^^^^^^^^^^^^
desec-stack-celery-email-1            |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
desec-stack-celery-email-1            |     return self.run(*args, **kwargs)
desec-stack-celery-email-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^
desec-stack-celery-email-1            |   File "/usr/src/app/desecapi/mail_backends.py", line 41, in _run_task
desec-stack-celery-email-1            |     return connection.send_messages(
desec-stack-celery-email-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^
desec-stack-celery-email-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 135, in send_messages
desec-stack-celery-email-1            |     sent = self._send(message)
desec-stack-celery-email-1            |            ^^^^^^^^^^^^^^^^^^^
desec-stack-celery-email-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 148, in _send
desec-stack-celery-email-1            |     from_email = sanitize_address(email_message.from_email, encoding)
desec-stack-celery-email-1            |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
desec-stack-celery-email-1            |   File "/usr/local/lib/python3.11/site-packages/django/core/mail/message.py", line 92, in sanitize_address
desec-stack-celery-email-1            |     raise ValueError(
desec-stack-celery-email-1            | ValueError: Invalid address; only deSEC <skript@sub.domain.de> could be parsed from "deSEC <skript@sub.domain.de>
desec-stack-celery-email-1            | "
desec-stack-celery-email-1            | [2023-12-31 11:54:43,731: WARNING/ForkPoolWorker-1] Sending queued email, details: {'lane': 'email_slow_lane'}
desec-stack-celery-email-1            | [2023-12-31 11:54:44,035: INFO/ForkPoolWorker-1] Task email_slow_lane[ebe99837-7cd7-4adb-9ac1-30a98169afbd] succeeded in 0.30483427399997254s: 1
```

Below my custom .env file:
```
# API-related
DESECSTACK_API_ADMIN=skript@sub.domain.de
DESECSTACK_API_AUTHACTION_VALIDITY=1
DESECSTACK_API_SEPA_CREDITOR_ID=
DESECSTACK_API_SEPA_CREDITOR_NAME=
DESECSTACK_API_EMAIL_HOST=xxxx.server.domain.de
DESECSTACK_API_EMAIL_HOST_USER=skript@sub.domain.de
DESECSTACK_API_EMAIL_HOST_PASSWORD=a9Z78@R2!SZp
DESECSTACK_API_EMAIL_PORT=587
DESECSTACK_API_SECRETKEY=TestTestTest
DESECSTACK_API_PSL_RESOLVER=9.9.9.9
DESECSTACK_API_PCH_API=https://desec.server.domain.de/pch/api
DESECSTACK_API_PCH_API_TOKEN=TestTestTest
DESECSTACK_DBAPI_PASSWORD_desec=TestTestTest
DESECSTACK_MINIMUM_TTL_DEFAULT=900
```

Also replaced the email address support@desec.io in the files [api/desecapi/templates/emails/from.txt](https://github.com/desec-io/desec-stack/blob/b9bbc080fed727eed520dd4815c090aba6b35a7f/api/desecapi/templates/emails/from.txt) and [api/api/settings.py](https://github.com/desec-io/desec-stack/blob/b9bbc080fed727eed520dd4815c090aba6b35a7f/api/api/settings.py#L162).

So currently I'm not sure, what is my configuration fault. So did anyone setup the stack with functionally sending email?

Happy new year,
Daniel

**Comment by peterthomassen** [comment]
I suspect you have a newline at the end of `api/desecapi/templates/emails/from.txt` which should not be there. Please try removing it :-)

I'm closing this, assuming that this is the solution. If it's not, please feel free to comment again on this issue!

**Comment by dwydler** [comment]
That was my first guess. In the file `api/desecapi/templates/emails/from.txt` are no empty lines. To be on the safe side i go to the end of the line, press multiple ENTF to see if there a any wild chars. After that i recreate the containers an try it again. The  error is still the same.

**Comment by peterthomassen** [comment]
The error message says it all:

> `ValueError('Invalid address; only deSEC <skript@sub.domain.de> could be parsed from "deSEC <skript@sub.domain.de>\n"')`

Note the `\n` at the end.

[Django emits this message](https://github.com/django/django/blob/a9094ec1f43dca7f2a649327afcd5e6226b4959c/django/core/mail/message.py#L90-L94) when Python's address parser returns a non-empty `rest` variable. You can verify yourself in a Python console that this `\n` indeed causes the condition to trigger:

```python
>>> from email.headerregistry import parser
>>> token, rest = parser.get_mailbox("deSEC <skript@sub.domain.de>")
>>> bool(rest)
False
>>> token, rest = parser.get_mailbox("deSEC <skript@sub.domain.de>\n")
>>> bool(rest)
True
```

You definitely have a problematic newline character there. To confirm, run `tail --byte 1 path/to/file | hexdump` on the command line. If the last byte in the file is `>`, you will see [ASCII code](https://ascii.bio/) `3e` in the output. If the last file is a newline, you'll see `0a` instead.

Some editors end all files with newlines regardless of what you type. If nothing else helps, perhaps can try another one.
